spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/seata?serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
server:
  port: 8085
  tomcat:
    max-connections: 10000
    max-threads: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.example.seataorder.model
